# ============================================
# CONFIGURACION BASE (siempre se carga)
# ============================================

# Identificacion
spring.application.name=financial-platform

# Jackson (formato fechas)
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=UTC

# Variables externas (se rellenan con .env)
dollar.api.base=${API_BASE:https://dolarapi.com/v1/dolares}
dollar.api.dollar-oficial=${VALUE_DOLLAR_OFICIAL:/oficial}
cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api.key=${CLOUDINARY_API_KEY}
cloudinary.api.secret=${CLOUDINARY_API_SECRET}
jwt.secret.key=${JWT_SECRET_KEY}

# ============================================
# PERFIL ACTIVO (local por defecto)
# ============================================
# Si no existe SPRING_PROFILES_ACTIVE en .env usa 'local'
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

